-- Daniel Lanches OS — Supabase Auth + locked RLS
-- Run in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  phone text not null default '',
  role text not null default 'customer'
    check (role in ('customer', 'employee', 'delivery', 'admin', 'super_admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.store_settings (
  id text primary key default 'default',
  store_open boolean not null default true,
  delivery_fee numeric(10,2) not null default 7.90,
  minimum_order numeric(10,2) not null default 25.00,
  updated_at timestamptz not null default now()
);

alter table public.store_settings
drop constraint if exists store_settings_singleton;

alter table public.store_settings
alter column id type text using id::text;

alter table public.store_settings
alter column id set default 'default';

alter table public.store_settings add column if not exists delivery_fee numeric(10,2) not null default 7.90;
alter table public.store_settings add column if not exists minimum_order numeric(10,2) not null default 25.00;

insert into public.store_settings (id, store_open)
values ('default', true)
on conflict (id) do nothing;

update public.store_settings
set id = 'default'
where id = '1'
  and not exists (select 1 from public.store_settings where id = 'default');

create table if not exists public.products (
  id text primary key,
  name text not null,
  category text not null,
  description text not null default '',
  price numeric(10,2) not null check (price >= 0),
  old_price numeric(10,2),
  badge text,
  available boolean not null default true,
  ingredients text not null default '',
  stock integer not null default 0 check (stock >= 0),
  prep_time text not null default '',
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products add column if not exists ingredients text not null default '';
alter table public.products add column if not exists stock integer not null default 0;
alter table public.products add column if not exists prep_time text not null default '';
alter table public.products add column if not exists featured boolean not null default false;

insert into public.products (id, name, category, description, price, old_price, badge, available, ingredients, stock, prep_time, featured)
values
  ('x-bacon', 'X Bacon Supremo', 'Destaque', 'Blend 160g, bacon crocante, cheddar e molho Daniel.', 39.90, 46.90, '-15%', true, 'blend, bacon, cheddar, alface, tomate, molho Daniel', 42, '18 min', true),
  ('combo-duplo', 'Duplo Daniel', 'Combo', 'Dois burgers, batata grande e bebida.', 68.90, 78.90, 'Combo', true, '2 burgers, batata grande, bebida', 25, '22 min', false),
  ('batata-cheddar', 'Batata cheddar', 'Extra', 'Porção crocante com cheddar cremoso e bacon.', 24.90, null, null, true, 'batata, cheddar, bacon', 30, '12 min', false),
  ('x-salada', 'X Salada Artesanal', 'Hambúrguer', 'Blend artesanal, queijo, alface, tomate e maionese da casa.', 34.90, null, null, true, 'blend, queijo, alface, tomate, maionese', 40, '18 min', false),
  ('x-tudo', 'X Tudo Daniel', 'Hambúrguer', 'Blend, presunto, ovo, bacon, queijo, salada e molho da casa.', 44.90, null, null, true, 'blend, presunto, ovo, bacon, queijo, salada', 30, '20 min', false),
  ('combo-familia', 'Família Premium', 'Combo', 'Quatro burgers, duas batatas e duas bebidas.', 139.90, 159.90, 'Família', true, '4 burgers, 2 batatas, 2 bebidas', 12, '28 min', false)
on conflict (id) do update
set name = excluded.name,
    category = excluded.category,
    description = excluded.description,
    price = excluded.price,
    old_price = excluded.old_price,
    badge = excluded.badge,
    available = excluded.available,
    ingredients = excluded.ingredients,
    stock = excluded.stock,
    prep_time = excluded.prep_time,
    featured = excluded.featured;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number bigint generated by default as identity (start with 1049 increment by 1) unique,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  status text not null default 'Novo'
    check (status in ('Novo', 'Em preparo', 'Saiu para entrega', 'Entregue', 'Cancelado')),
  customer_name text not null,
  phone text not null,
  address text not null,
  delivery_mode text not null default 'Entrega no endereço',
  items jsonb not null default '[]'::jsonb,
  notes text not null default '-',
  payment text not null default 'Pix',
  change_for text not null default '-',
  delivery_fee numeric(10,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Migration support if you already ran the previous MVP schema.
alter table public.orders add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.orders add column if not exists order_number bigint;
alter table public.orders add column if not exists updated_at timestamptz not null default now();
create sequence if not exists public.orders_order_number_seq start with 1049 increment by 1;
update public.orders
set order_number = nextval('public.orders_order_number_seq')
where order_number is null;
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'orders'
      and column_name = 'order_number'
      and is_identity = 'NO'
  ) then
    alter table public.orders
    alter column order_number set default nextval('public.orders_order_number_seq');
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'orders_order_number_key'
  ) then
    alter table public.orders add constraint orders_order_number_key unique (order_number);
  end if;
end $$;

create index if not exists profiles_role_idx on public.profiles (role);
create index if not exists profiles_phone_idx on public.profiles (phone);
create index if not exists products_available_idx on public.products (available);
create index if not exists orders_user_id_idx on public.orders (user_id);
create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_phone_idx on public.orders (phone);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select role from public.profiles where id = auth.uid()), 'anonymous')
$$;

create or replace function public.current_user_phone()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select phone from public.profiles where id = auth.uid()), '')
$$;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_user_role() in ('employee', 'delivery', 'admin', 'super_admin')
$$;

create or replace function public.validate_order_totals()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  product_row public.products%rowtype;
  requested_id text;
  requested_qty integer;
  normalized_items jsonb := '[]'::jsonb;
  subtotal numeric(10,2) := 0;
  config public.store_settings%rowtype;
begin
  select * into config
  from public.store_settings
  where id = 'default';

  if config.id is null then
    raise exception 'Configuração da loja não encontrada';
  end if;

  if new.items is null or jsonb_typeof(new.items) <> 'array' or jsonb_array_length(new.items) = 0 then
    raise exception 'Pedido sem itens';
  end if;

  for item in select * from jsonb_array_elements(new.items)
  loop
    requested_id := item ->> 'id';
    if requested_id is null or requested_id = '' then
      raise exception 'Item sem produto';
    end if;

    if coalesce(item ->> 'qty', '') !~ '^[0-9]+$' then
      raise exception 'Quantidade inválida para o produto %', requested_id;
    end if;

    requested_qty := (item ->> 'qty')::integer;

    if requested_qty < 1 or requested_qty > 99 then
      raise exception 'Quantidade inválida para o produto %', requested_id;
    end if;

    select * into product_row
    from public.products
    where id = requested_id and available = true;

    if product_row.id is null then
      raise exception 'Produto indisponível ou inexistente: %', requested_id;
    end if;

    if product_row.stock < requested_qty then
      raise exception 'Estoque insuficiente para o produto %', requested_id;
    end if;

    subtotal := subtotal + (product_row.price * requested_qty);
    normalized_items := normalized_items || jsonb_build_array(jsonb_build_object(
      'id', product_row.id,
      'name', product_row.name,
      'price', product_row.price,
      'qty', requested_qty
    ));
  end loop;

  if subtotal < config.minimum_order then
    raise exception 'Pedido mínimo não atingido. Mínimo: R$ %', config.minimum_order;
  end if;

  new.items := normalized_items;
  if new.delivery_mode = 'Retirada no local' then
    new.delivery_fee := 0;
  else
    new.delivery_fee := config.delivery_fee;
  end if;

  return new;
end;
$$;

create or replace function public.decrement_stock_after_order()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  requested_id text;
  requested_qty integer;
begin
  for item in select * from jsonb_array_elements(new.items)
  loop
    requested_id := item ->> 'id';
    requested_qty := (item ->> 'qty')::integer;

    update public.products
    set stock = stock - requested_qty,
        updated_at = now()
    where id = requested_id;

    if not found then
      raise exception 'Produto não encontrado para descontar estoque: %', requested_id;
    end if;
  end loop;

  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

drop trigger if exists orders_validate_totals on public.orders;
create trigger orders_validate_totals
before insert or update of items, delivery_mode, delivery_fee on public.orders
for each row execute function public.validate_order_totals();

drop trigger if exists orders_decrement_stock on public.orders;
create trigger orders_decrement_stock
after insert on public.orders
for each row execute function public.decrement_stock_after_order();

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists store_settings_set_updated_at on public.store_settings;
create trigger store_settings_set_updated_at
before update on public.store_settings
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.store_settings enable row level security;

-- Remove every permissive policy from the previous MVP schema.
drop policy if exists "mvp_orders_select" on public.orders;
drop policy if exists "mvp_orders_insert" on public.orders;
drop policy if exists "mvp_orders_update" on public.orders;
drop policy if exists "mvp_orders_delete" on public.orders;
drop policy if exists "public read orders" on public.orders;
drop policy if exists "public insert orders" on public.orders;
drop policy if exists "public update orders" on public.orders;
drop policy if exists "public delete orders" on public.orders;
drop policy if exists "mvp_settings_select" on public.store_settings;
drop policy if exists "mvp_settings_upsert" on public.store_settings;
drop policy if exists "public read store_settings" on public.store_settings;
drop policy if exists "public update store_settings" on public.store_settings;

drop policy if exists "profiles_select_own_or_staff" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own_customer" on public.profiles;
drop policy if exists "profiles_update_admin" on public.profiles;
create policy "profiles_select_own_or_staff"
  on public.profiles for select
  using (id = auth.uid() or public.is_staff());
create policy "profiles_insert_own"
  on public.profiles for insert
  with check (id = auth.uid() and role = 'customer');
create policy "profiles_update_own_customer"
  on public.profiles for update
  using (id = auth.uid() and role = 'customer')
  with check (id = auth.uid() and role = 'customer');
create policy "profiles_update_admin"
  on public.profiles for update
  using (public.current_user_role() in ('admin', 'super_admin'))
  with check (public.current_user_role() in ('admin', 'super_admin'));

drop policy if exists "products_read_available" on public.products;
drop policy if exists "products_manage_admin" on public.products;
create policy "products_read_available"
  on public.products for select
  using (available = true or public.current_user_role() in ('admin', 'super_admin'));
create policy "products_manage_admin"
  on public.products for all
  using (public.current_user_role() in ('admin', 'super_admin'))
  with check (public.current_user_role() in ('admin', 'super_admin'));

drop policy if exists "settings_read_all" on public.store_settings;
drop policy if exists "settings_update_staff" on public.store_settings;
create policy "settings_read_all"
  on public.store_settings for select
  using (true);
create policy "settings_update_staff"
  on public.store_settings for update
  using (public.is_staff())
  with check (public.is_staff());

-- SECURITY FIX: policies used to also allow access via
-- `phone = public.current_user_phone()`. Since `phone` is a free-text field
-- customers can edit on their own profile (see profiles_update_own_customer),
-- anyone could set their phone to match another customer's and read/insert
-- into their order history. Authorization now relies only on `user_id`,
-- which is set by Supabase Auth and cannot be forged by the client.
drop policy if exists "orders_select_own_or_staff" on public.orders;
drop policy if exists "orders_insert_own" on public.orders;
drop policy if exists "orders_insert_staff" on public.orders;
drop policy if exists "orders_update_staff_only" on public.orders;
drop policy if exists "orders_delete_admin_only" on public.orders;
create policy "orders_select_own_or_staff"
  on public.orders for select
  using (public.is_staff() or user_id = auth.uid());
create policy "orders_insert_own"
  on public.orders for insert
  with check (
    auth.uid() is not null
    and user_id = auth.uid()
  );
create policy "orders_insert_staff"
  on public.orders for insert
  with check (public.is_staff());
create policy "orders_update_staff_only"
  on public.orders for update
  using (public.is_staff())
  with check (public.is_staff());
create policy "orders_delete_admin_only"
  on public.orders for delete
  using (public.current_user_role() in ('admin', 'super_admin'));

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'orders'
  ) then
    alter publication supabase_realtime add table public.orders;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'store_settings'
  ) then
    alter publication supabase_realtime add table public.store_settings;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'products'
  ) then
    alter publication supabase_realtime add table public.products;
  end if;
end $$;

-- Promote an admin manually after creating/signing up the admin user:
-- update public.profiles set role = 'admin' where id = '<USER_UUID>';
